FROM python:3.10-slim-buster

# Install dependencies, like curl, if required for further setup
RUN apt-get update && apt-get install -y curl

# Install pip dependencies
RUN pip install --no-cache-dir -U pip setuptools wheel

# Uninstall and install specific version of webdataset
RUN pip install webdataset==0.2.100 && \
    pip install boto3==1.35.66